spring:
  profiles:
    active:
    - dev
---
server:
  port: 8000
spring:
  profiles: dev
  application:
    name: hsrm-config-eureka
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false       # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/  # Erueka服务器地址，其他微服务向该Eureka中注册时需要这个地址

---
server:
  port: 8000
spring:
  profiles: test
  application:
    name: hsrm-config-eureka
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false       # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/  # Erueka服务器地址，其他微服务向该Eureka中注册时需要这个地址

