spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev   # 开发环境
  application:
    name: hsrm-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
---
server:
  port: 8202
spring:
  profiles: test   # 开发环境
  application:
    name: hsrm-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

